### ISSUE TITLE
Broken hero image on onehomeowner.com/agents 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/onehomeowner.com-agents#1]
@codextiny Can you please look into this issue on the home page ?

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/ee998678-647e-40f4-befa-ca0bd9265048">

support@homeowner.ai 
M!l3st0nesL@bs

**Comment by codextiny** [comment]
@shannonbaldwin 

Its done, please check
